### ISSUE TITLE
no-dupe-keys in Mongo Query

### ISSUE THREAD

**Issue by eltoro** [keithamus/eslint-config-strict#28]
Found one instance where this causes a problem. When building a dynamic mongo query operators such as $or may need to be duplicated. Unless there's another way to write it.

```js
const query = {
    id: input.id,
    state: input.state,
    $or: [
      {
        floodZone: { $exists: false }
      },
      {
        floodZone: { $exists: true, $in: [input.floodZone] }
      }
    ],
    $or: [
      {
        yearBuilt: { $exists: false }
      },
      {
        'yearBuilt.max': { $exists: true, $lte: input.yearBuilt }
      }
    ]
  };
```

**Comment by keithamus** [comment]
Hmm interesting. Does that even work? Just running that in a REPL - only the last $or is defined, not the first.

**Comment by keithamus** [comment]
Going to close this because of inactivity. Let me know if you're still interested in this and we can re-open.
