### ISSUE TITLE
prefer-reflect is deprecated

### ISSUE THREAD

**Issue by lydell** [keithamus/eslint-config-strict#30]
http://eslint.org/docs/rules/prefer-reflect

> This rule was deprecated in ESLint v3.9.0 and will not be replaced. The original intent of this rule now seems misguided as we have come to understand that Reflect methods are not actually intended to replace the Object counterparts the rule suggests, but rather exist as low-level primitives to be used with proxies in order to replicate the default behavior of various previously existing functionality.

**Comment by keithamus** [comment]
Feel free to PR!

**Comment by lydell** [comment]
Ok, I’ll do that when I figure out the commit log convention :)

The no-negated-in-lhs is also deprecated. I’ll probably do that one as well while at it.

http://eslint.org/docs/rules/no-negated-in-lhs

> This rule was deprecated in ESLint v3.3.0 and replaced by the no-unsafe-negation rule.

**Comment by keithamus** [comment]
Cool. Commit convention for relaxing a rule is just `fix: relax <the-rule>`, but feel free to PR with whatever you want and I can just squash/reword the commits 😄

**Comment by lydell** [comment]
There we go. #31 is a PR for removing prefer-reflect, #32 is for discussing no-negated-in-lhs / no-unsafe-negation.
