### ISSUE TITLE
no-negated-in-lhs / no-unsafe-negation

### ISSUE THREAD

**Issue by lydell** [keithamus/eslint-config-strict#32]
rules/no-negated-in-lhs.md exists, but no-negated-in-lhs does not seem to be mentioned anywhere else. That rule is also deprecated and replaced by [no-unsafe-negation](http://eslint.org/docs/rules/no-unsafe-negation). That feels like a very useful rule, which I'd like to see enabled in eslint-config-strict.

I would have made a PR if I would have know what to do here :)

**Comment by keithamus** [comment]
Yes documentation is a bit sparse... I think I might just delete it and instead have some quick one-liners around justifications for each rule. Feel free to take the initiative here and do what you feel is right.

As for adding `no-unsafe-negation` as a rule, I'm happy to see it added. Some words on code style... the rules in the ES5.js file are sorted by the order they appear on the website. Copy/paste the description of the rule and add it as a comment above the rule in ES5.js.

For commit style for new rules - take a look [at](https://github.com/keithamus/eslint-config-strict/commit/74df3f31394fbe3ecc8bbe05b03d0134f93744e1) [these](https://github.com/keithamus/eslint-config-strict/commit/c7aca0397c641fbb043a859972aac473066ebdb8) [examples](https://github.com/keithamus/eslint-config-strict/commit/a25ffda1a7c86944251b5258135277c8980c3681), basically:

```
feat: add <rule> rule

BREAKING CHANGE:

Code that violates <the rule> will now fail eslint.
```

**Comment by keithamus** [comment]
FWIW if you see a missing rule in the config I'm happy to see it added (unless there is a very good reason as to why its not already there, but those are usually set to explicitly `0` in the code).
